# Generated by Django 6.0.5 on 2026-05-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FieldLogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(db_index=True, max_length=128)),
                ("activity_name", models.CharField(db_index=True, max_length=128)),
                ("activity_id", models.CharField(db_index=True, max_length=128)),
                ("user_id", models.CharField(db_index=True, max_length=64)),
                ("key", models.CharField(db_index=True, max_length=128)),
                ("value", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="FieldEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(db_index=True, max_length=128)),
                ("activity_name", models.CharField(db_index=True, max_length=128)),
                ("activity_id", models.CharField(db_index=True, max_length=128)),
                ("user_id", models.CharField(db_index=True, max_length=64)),
                ("key", models.CharField(db_index=True, max_length=128)),
                ("value", models.TextField()),
            ],
            options={
                "unique_together": {
                    ("course_id", "activity_name", "activity_id", "user_id", "key")
                },
            },
        ),
        migrations.CreateModel(
            name="PendingEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(db_index=True, max_length=128)),
                ("activity_id", models.CharField(db_index=True, max_length=128)),
                ("event_name", models.CharField(max_length=255)),
                ("event_value", models.TextField()),
                ("event_context", models.TextField()),
                ("event_permission", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["course_id", "activity_id", "id"],
                        name="pxc_xblock__course__c9c89f_idx",
                    )
                ],
            },
        ),
    ]
